### ISSUE TITLE
Question getting started

### ISSUE THREAD

**Issue by lawrence-c** [kaushikgopal/henry-hugo#3]
Hey,

I'm quite new to Hugo, and was having a play around with some various themes, and came across this one which looked awesome which I wanted to try out - however hit some issues on getting started with the `henry` theme.

Using Hugo on WSL:
```
hugo v0.105.0+extended linux/amd64 BuildDate=unknown
```
---

I created a new site: 
```
hugo new site quickstart
```

Added the `henry` theme: 
```
cd quickstart
git clone git@github.com:kaushikgopal/henry-hugo.git themes/henry
```

Updated the `config.toml` with:
```
theme = "henry"
```

Ran hugo:
```
hugo server -D
open http://localhost:1313/
```

However I see the following:
![image](https://user-images.githubusercontent.com/10439579/200692978-188c2204-ce72-47e0-9769-d291a8a3fe6e.png)

and nothing else.

I tried creating a new post with:
```
hugo new posts/my-first-post.md
```

however, nothing changed.

I have tried using a different theme (`ananke`), and that did render okay.

Am I missing something?

Thanks in advance :)

**Comment by sandeshbhusal** [comment]
Having the same issue on my end as well. All other themes work except this one :(

**Comment by maijau** [comment]
same for me. Can't figure out what needs to be different. A few hints as to how to create a page structure with about, blog, and posts shown would be appreciated.

**Comment by kaushikgopal** [comment]
Sorry I seemed to have missed all these comments. Got to setup notifications for issues 🤔.

Let me try to add some documentation and ping this thread.

**Comment by kaushikgopal** [comment]
@lawrence-c  @sandeshbhusal @maijau : If you follow [the instructions](https://github.com/kaushikgopal/henry-hugo#getting-started) now, it should be much easier.

i've also added some sample posts that will automatically show up. hope that fixes it!

**Comment by kaushikgopal** [comment]
I added a fix for a bug that was making things unnecessarily complicated, so make sure to pull the latest version of the theme 🙏

**Comment by lawrence-c** [comment]
Thanks @kaushikgopal - will give it a try later on :)

**Comment by frankenstein91** [comment]
@kaushikgopal how would oyu add an imprint/impressum?

**Comment by kaushikgopal** [comment]
> @kaushikgopal how would oyu add an imprint/impressum?

Can you elaborate what that is? (Also feel free to raise a separate issue 🙏) if it's not related from this specific one.
